<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class MahasiswaSeeder extends Seeder
{
    public function run()
    {
        // Create users for mahasiswa first
        $userIds = [];
        $emails = [
            'ahmad.fauzi@student.lp3i.ac.id',
            'siti.nurhaliza@student.lp3i.ac.id',
            'budi.santoso@student.lp3i.ac.id',
            'dewi.lestari@student.lp3i.ac.id',
            'rizky.pratama@student.lp3i.ac.id',
        ];
        $names = [
            'Ahmad Fauzi',
            'Siti Nurhaliza',
            'Budi Santoso',
            'Dewi Lestari',
            'Rizky Pratama',
        ];

        foreach ($emails as $index => $email) {
            $userId = DB::table('users')->insertGetId([
                'name' => $names[$index],
                'email' => $email,
                'password' => Hash::make('password123'),
                'role' => 'mahasiswa',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
            $userIds[] = $userId;
        }

        // Get kelas IDs
        $kelasASE10 = DB::table('kelas')->where('nama_kelas', 'ASE10')->value('id_kelas');
        $kelasAIS12 = DB::table('kelas')->where('nama_kelas', 'AIS12')->value('id_kelas');
        $kelasOAA13A = DB::table('kelas')->where('nama_kelas', 'OAA13 A')->value('id_kelas');

        DB::table('mahasiswa')->insert([
            [
                'nipd' => '2407810070001',
                'nama_mhs' => 'Ahmad Fauzi',
                'alamat' => 'Jl. Merdeka No. 10, Bandung',
                'domisili' => 'Bandung',
                'tempat_lahir' => 'Bandung',
                'tgl_lahir' => '2005-03-15',
                'angkatan' => 2024,
                'periode' => '2024/2025',
                'email' => 'ahmad.fauzi@student.lp3i.ac.id',
                'agama' => 'Islam',
                'no_tlp' => '081234567001',
                'tahun_lulus' => null,
                'kecamatan' => 'Coblong',
                'desa' => 'Dago',
                'kode_pos' => '40135',
                'jenis_kelamin' => 'L',
                'jenis_kelas' => 'Reguler',
                'status_verifikasi' => 'verified',
                'payment_status' => 'paid',
                'payment_method' => 'transfer',
                'payment_proof_path' => null,
                'payment_bank_origin' => 'BCA',
                'payment_account_name' => 'Bapak Fauzi',
                'payment_sender_name' => 'Bapak Fauzi',
                'payment_transfer_date' => '2024-08-01',
                'payment_expires_at' => null,
                'payment_amount' => 5000000,
                'asal_sekolah' => 'SMAN 3 Bandung',
                'file_path' => null,
                'ktp_path' => null,
                'akte_kelahiran_path' => null,
                'ijazah_path' => null,
                'surat_sudah_bekerja_path' => null,
                'instagram_path' => null,
                'nama_wali' => 'Bapak Fauzi',
                'telp_wali' => '081234560001',
                'pekerjaan_wali' => 'Wiraswasta',
                'whatsapp_wali' => '081234560001',
                'foto' => null,
                'status' => 'Aktif',
                'id_user' => $userIds[0],
                'id_program_studi' => 2, // ASE
                'id_kelas' => null, // Sudah punya kelas
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nipd' => '2407810070002',
                'nama_mhs' => 'Siti Nurhaliza',
                'alamat' => 'Jl. Asia Afrika No. 25, Bandung',
                'domisili' => 'Bandung',
                'tempat_lahir' => 'Jakarta',
                'tgl_lahir' => '2005-07-22',
                'angkatan' => 2024,
                'periode' => '2024/2025',
                'email' => 'siti.nurhaliza@student.lp3i.ac.id',
                'agama' => 'Islam',
                'no_tlp' => '081234567002',
                'tahun_lulus' => null,
                'kecamatan' => 'Lengkong',
                'desa' => 'Burangrang',
                'kode_pos' => '40261',
                'jenis_kelamin' => 'P',
                'jenis_kelas' => 'Reguler',
                'status_verifikasi' => 'verified',
                'payment_status' => 'paid',
                'payment_method' => 'transfer',
                'payment_proof_path' => null,
                'payment_bank_origin' => 'Mandiri',
                'payment_account_name' => 'Ibu Haliza',
                'payment_sender_name' => 'Ibu Haliza',
                'payment_transfer_date' => '2024-08-05',
                'payment_expires_at' => null,
                'payment_amount' => 5000000,
                'asal_sekolah' => 'SMAN 5 Jakarta',
                'file_path' => null,
                'ktp_path' => null,
                'akte_kelahiran_path' => null,
                'ijazah_path' => null,
                'surat_sudah_bekerja_path' => null,
                'instagram_path' => null,
                'nama_wali' => 'Ibu Haliza',
                'telp_wali' => '081234560002',
                'pekerjaan_wali' => 'PNS',
                'whatsapp_wali' => '081234560002',
                'foto' => null,
                'status' => 'Aktif',
                'id_user' => $userIds[1],
                'id_program_studi' => 1, // AIS
                'id_kelas' => null, // Sudah punya kelas
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nipd' => '2407810070003',
                'nama_mhs' => 'Budi Santoso',
                'alamat' => 'Jl. Dago No. 50, Bandung',
                'domisili' => 'Bandung',
                'tempat_lahir' => 'Surabaya',
                'tgl_lahir' => '2004-11-08',
                'angkatan' => 2024,
                'periode' => '2024/2025',
                'email' => 'budi.santoso@student.lp3i.ac.id',
                'agama' => 'Kristen',
                'no_tlp' => '081234567003',
                'tahun_lulus' => null,
                'kecamatan' => 'Coblong',
                'desa' => 'Dago',
                'kode_pos' => '40135',
                'jenis_kelamin' => 'L',
                'jenis_kelas' => 'Reguler',
                'status_verifikasi' => 'verified',
                'payment_status' => 'paid',
                'payment_method' => 'transfer',
                'payment_proof_path' => null,
                'payment_bank_origin' => 'BRI',
                'payment_account_name' => 'Bapak Santoso',
                'payment_sender_name' => 'Bapak Santoso',
                'payment_transfer_date' => '2024-08-10',
                'payment_expires_at' => null,
                'payment_amount' => 5000000,
                'asal_sekolah' => 'SMAN 1 Surabaya',
                'file_path' => null,
                'ktp_path' => null,
                'akte_kelahiran_path' => null,
                'ijazah_path' => null,
                'surat_sudah_bekerja_path' => null,
                'instagram_path' => null,
                'nama_wali' => 'Bapak Santoso',
                'telp_wali' => '081234560003',
                'pekerjaan_wali' => 'Dokter',
                'whatsapp_wali' => '081234560003',
                'foto' => null,
                'status' => 'Aktif',
                'id_user' => $userIds[2],
                'id_program_studi' => 3, // OAA
                'id_kelas' => null, // Sudah punya kelas
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nipd' => '2407810070004',
                'nama_mhs' => 'Dewi Lestari',
                'alamat' => 'Jl. Pasteur No. 100, Bandung',
                'domisili' => 'Bandung',
                'tempat_lahir' => 'Bandung',
                'tgl_lahir' => '2005-01-30',
                'angkatan' => 2024,
                'periode' => '2024/2025',
                'email' => 'dewi.lestari@student.lp3i.ac.id',
                'agama' => 'Islam',
                'no_tlp' => '081234567004',
                'tahun_lulus' => null,
                'kecamatan' => 'Cicendo',
                'desa' => 'Pasteur',
                'kode_pos' => '40171',
                'jenis_kelamin' => 'P',
                'jenis_kelas' => 'Reguler',
                'status_verifikasi' => 'pending',
                'payment_status' => 'unpaid',
                'payment_method' => null,
                'payment_proof_path' => null,
                'payment_bank_origin' => null,
                'payment_account_name' => null,
                'payment_sender_name' => null,
                'payment_transfer_date' => null,
                'payment_expires_at' => null,
                'payment_amount' => null,
                'asal_sekolah' => 'SMAN 2 Bandung',
                'file_path' => null,
                'ktp_path' => null,
                'akte_kelahiran_path' => null,
                'ijazah_path' => null,
                'surat_sudah_bekerja_path' => null,
                'instagram_path' => null,
                'nama_wali' => 'Ibu Lestari',
                'telp_wali' => '081234560004',
                'pekerjaan_wali' => 'Guru',
                'whatsapp_wali' => '081234560004',
                'foto' => null,
                'status' => 'Aktif',
                'id_user' => $userIds[3],
                'id_program_studi' => 2, // ASE
                'id_kelas' => null, // Sudah punya kelas
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nipd' => '2407810070005',
                'nama_mhs' => 'Rizky Pratama',
                'alamat' => 'Jl. Setiabudi No. 75, Bandung',
                'domisili' => 'Bandung',
                'tempat_lahir' => 'Cirebon',
                'tgl_lahir' => '2005-05-18',
                'angkatan' => 2024,
                'periode' => '2024/2025',
                'email' => 'rizky.pratama@student.lp3i.ac.id',
                'agama' => 'Islam',
                'no_tlp' => '081234567005',
                'tahun_lulus' => null,
                'kecamatan' => 'Cidadap',
                'desa' => 'Setiabudi',
                'kode_pos' => '40154',
                'jenis_kelamin' => 'L',
                'jenis_kelas' => 'Reguler',
                'status_verifikasi' => 'pending',
                'payment_status' => 'unpaid',
                'payment_method' => null,
                'payment_proof_path' => null,
                'payment_bank_origin' => null,
                'payment_account_name' => null,
                'payment_sender_name' => null,
                'payment_transfer_date' => null,
                'payment_expires_at' => null,
                'payment_amount' => null,
                'asal_sekolah' => 'SMAN 1 Cirebon',
                'file_path' => null,
                'ktp_path' => null,
                'akte_kelahiran_path' => null,
                'ijazah_path' => null,
                'surat_sudah_bekerja_path' => null,
                'instagram_path' => null,
                'nama_wali' => 'Bapak Pratama',
                'telp_wali' => '081234560005',
                'pekerjaan_wali' => 'Pengusaha',
                'whatsapp_wali' => '081234560005',
                'foto' => null,
                'status' => 'Aktif',
                'id_user' => $userIds[4],
                'id_program_studi' => 3, // OAA
                'id_kelas' => null, // Sudah punya kelas
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
